name: mlsearch
channels:
  - pytorch
  - nvidia
  - comet_ml
  - conda-forge
  - defaults
dependencies:
  - attrs
  - av2
  - comet_ml
  - numpy
  - plotly
  - python=3.10
  - pytorch
  - pytorch-cuda=12.1
  - pytorch-lightning
  - shapely
  - streamlit
  - tqdm
